---
title: "Projet - Analyse"
output: html_notebook
---

# Projet KikiCkisenVa - Analyse

\section{Recuperation des donnees}
```{r}
data_train <- read.csv("spreedsheets/data_train.csv", header = TRUE)
data_train <-na.omit(data_train)
dim(data_train)
head(data_train)
```
```{r}
data_train_num <- data_train[, unlist(lapply(data_train, is.numeric))]
data_train_num[26] <- data_train["Attrition"]
dim(data_train_num)
head(data_train_num)
```

\section{Stats descriptives}
```{r}
chisq.test(data_train_num[-26])
```
Toutes les variables ne semblent pas indépentantes entre elles.




\section{ACP}
```{r}
library(FactoMineR)
res <- PCA(data_train_num, scale.unit = TRUE, graph = FALSE, quali.sup = 26)
plot(res, choix = "ind", habillage = 26, select = FALSE, unselect = 0)
plot(res, choix = "var", cex = 0.8)
```

\subsection{Equilibrage des Donnees}
```{r}
data_train_log <- log(data_train_num[,-26])
data_train_log[data_train_log == -Inf] <- 0
data_train_log <- t(scale(t(data_train_log)))
data_train_log <- as.data.frame(data_train_log)
data_train_log[26] <- data_train["Attrition"]

head(data_train_log)
```
```{r}
res <- PCA(data_train_log, scale.unit = TRUE, graph = FALSE, quali.sup = 26)
plot(res, choix = "ind", habillage = 26, select = FALSE, unselect = 0)
plot(res, choix = "var", cex = 0.7)
```

\subsection
```{r}
plot(res, select="cos2 0.7", choix="ind", habillage = 26)
plot(res, select="contrib 5", choix="ind", habillage = 26)
```
```{r}
res$eig
barplot(res$eig[,2])
```










