---
title: "Nouveau"
author: "Michele Bona"
date: "28/05/2021"
output: html_document
---

```{r}
data_train <- read.csv("data_train.csv", header = TRUE)
data_train <-na.omit(data_train)
head(data_train)
```
```{r}
data_train_num <- data_train[, unlist(lapply(data_train, is.numeric))]
data_train_num[26] <- data_train["Attrition"]
head(data_train_num)
```


```{r}
dim(data_train_num)
```
```{r}
chisq.test(data_train_num[-26])
```
Toutes les variables ne semblent pas indépentantes entre elles.
\section{Stats descriptives}
```{r}
summary(data_train_num)
```

\section{ACP}

```{r}
library(FactoMineR)
res <- PCA(data_train_num, scale.unit=TRUE, graph = FALSE, quali.sup = 26)
plot(res, choix = "ind", habillage = 26, select=FALSE, unselect=0)
plot(res, choix="var", cex = 0.8)
```


```{r}
data_train_log <- log(data_train_num[,-26])
data_train_log[data_train_log == -Inf] = 0
data_train_log = t(scale(t(data_train_log)))
data_train_log = as.data.frame(data_train_log)
data_train_log[26] <- data_train["Attrition"]

head(data_train_log)
```

```{r}
res <- PCA(data_train_log, scale.unit=TRUE, graph = FALSE, quali.sup = 26)
plot(res, choix = "ind", habillage = 26, select=FALSE, unselect=0)
plot(res, choix="var", cex = 0.7)
```

```{r}
plot(res, select="cos2 0.7", choix="ind", habillage = 26)
plot(res, select="contrib 5", choix="ind", habillage = 26)
```

```{r}
res$eig
barplot(res$eig[,2])
```

L'inertie de chaque composante en pourcentage. On remarque que les 2 premiers suffisent car les autres apportent moins de 10%...

```{r}
plot(res, choix="ind", select = "cos2 0.5", habillage = 26, axes=c(1,3))
#plot(res, select="contrib 5", choix="ind", habillage = 26)
```
```{r}
res$var$contrib[,1:2]
```

```{r}
median(res$var$contrib[,1])
median(res$var$contrib[,2])
```

```{r}
aled <- (res$var$contrib[,1] > median(res$var$contrib[,1])) | (res$var$contrib[,2] > median(res$var$contrib[,2]))
aled
```

```{r}

```

